# Generated by Django 5.1.6 on 2025-02-20 11:20

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Названия блюда")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Цена указывается в рублях",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                        verbose_name="Цена",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание блюда")),
            ],
            options={
                "verbose_name": "Блюдо",
                "verbose_name_plural": "Блюда",
                "ordering": ("name",),
            },
        ),
    ]
