# Generated by Django 5.1.6 on 2025-02-20 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dishes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveSmallIntegerField(unique=True, verbose_name="Номер стола")),
                (
                    "quantity_seat",
                    models.CharField(
                        choices=[
                            ("1 персона", "1 персона"),
                            ("2 персоны", "2 персоны"),
                            ("3 персоны", "3 персоны"),
                            ("4 персоны", "4 персоны"),
                            ("5 персон", "5 персон"),
                        ],
                        default="1 персона",
                        max_length=20,
                        verbose_name="Количество мест за столом",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Цена указывается в рублях",
                        max_digits=10,
                        null=True,
                        verbose_name="Общая стоимость заказа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("В ожидании", "В ожидании"), ("Готово", "Готово"), ("Оплачено", "Оплачено")],
                        default="В ожидании",
                        max_length=20,
                        verbose_name="Статус заказа",
                    ),
                ),
                ("order_datetime", models.DateTimeField(auto_now_add=True, verbose_name="Время заказа")),
                ("items", models.ManyToManyField(to="dishes.dish", verbose_name="Блюда")),
                (
                    "table_number",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.table",
                        verbose_name="Номер стола",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ("-order_datetime",),
            },
        ),
    ]
